# Super legacy. This only runs locally and rather than trying to get it to work
# just committing the files and deploying.
name: Deploy to Dist

on:
  push:
    branches:
      - craft-v2

jobs:
  deploy_to_dist:
    name: Copy dist files to master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-branch

      - name: Copy dist files to master
        run: |
          rm -rf master-branch/dist/docs/craft-v2/*
          mkdir -p master-branch/dist/docs/craft-v2/
          cp -r docs/.vuepress/dist/* master-branch/dist/docs/craft-v2/

      - name: Commit and push changes
        run: |
          cd master-branch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git diff --staged --quiet || git commit -m "Deploy docs build from ${{ github.sha }}"
          git push origin master
