# DOCUMENT_ROOT is the file path on the server up to the public folder
# with a trailing slash. Add 'public/' to target public folder.
# /server/path_html (default)
# TARGET: ${{ secrets.DOCUMENT_ROOT }}/public/docs/craft-v2/ (subfolder)

name: Deploy v2 Docs

on:
  push:
    branches:
      - craft-v2

jobs:
  build_and_deploy_files:
    name: Deploy committed files (built locally)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Deploy files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DOCUMENT_ROOT }}/docs/craft-v2/
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/.vuepress/dist/"
